### ISSUE TITLE
Mutation pane failing with "TypeError: Markdown.__init__() got an unexpected keyword argument 'style'"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsqc#163]
When clicking on the mutations pane after loading the following tree sequence:

```
ts = msprime.simulate(10, Ne=1e4, length=10e6, recombination_rate=1e-8, mutation_rate=1e-8)
ts.dump("foo.trees")
```

I get:

```
2024-07-14 08:47:21,507 [80984] ERROR    tornado.application: Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x10e026da0>>, <Task finished name='Task-103' coro=<async_execute.<locals>.wrapper() done, defined at /Users/yan/miniforge3/lib/python3.10/site-packages/panel/io/server.py:170> exception=TypeError("Markdown.__init__() got an unexpected keyword argument 'style'")>)
Traceback (most recent call last):
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tsqc/__main__.py", line 58, in show
    content = pages.PAGES_MAP[page_name].page(tsm)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tsqc/pages/mutations.py", line 228, in page
    return pn.Column(plot_options, muts_panel)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/layout/base.py", line 820, in __init__
    params['objects'] = [panel(pane) for pane in objects]
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/layout/base.py", line 820, in <listcomp>
    params['objects'] = [panel(pane) for pane in objects]
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/pane/base.py", line 86, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/param.py", line 814, in __init__
    self._replace_pane()
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/param.py", line 882, in _replace_pane
    new_object = self.eval(self.object)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/param.py", line 1097, in eval
    return eval_function_with_deps(ref)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/reactive.py", line 594, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tsqc/pages/mutations.py", line 20, in make_muts_panel
    muts_df = tsm.mutations_df
  File "/Users/yan/miniforge3/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tsqc/cache.py", line 33, in wrapper
    result = func(self, *args, **kwargs)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tsqc/model.py", line 464, in mutations_df
    metadata_dict = json.loads(pop.metadata.decode("utf-8"))
  File "/Users/yan/miniforge3/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/yan/miniforge3/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/yan/miniforge3/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/io/server.py", line 176, in wrapper
    state._handle_exception(e)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/io/state.py", line 458, in _handle_exception
    raise exception
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/io/server.py", line 174, in wrapper
    return await func(*args, **kw)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/param.py", line 865, in _eval_async
    raise e
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/param.py", line 844, in _eval_async
    async for new_obj in awaitable:
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/util/__init__.py", line 502, in to_async_gen
    value = await asyncio.to_thread(safe_next)
  File "/Users/yan/miniforge3/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/Users/yan/miniforge3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/util/__init__.py", line 497, in safe_next
    return next(sync_gen)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/reactive.py", line 568, in wrapped
    for val in evaled:
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/tsqc/__main__.py", line 65, in show
    error_panel = pn.pane.Markdown(
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/pane/base.py", line 160, in __init__
    super().__init__(object=object, **params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/reactive.py", line 559, in __init__
    super().__init__(**params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/reactive.py", line 119, in __init__
    super().__init__(**params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/viewable.py", line 699, in __init__
    super().__init__(**params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/viewable.py", line 538, in __init__
    super().__init__(**params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/panel/viewable.py", line 299, in __init__
    super().__init__(**params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/parameterized.py", line 4188, in __init__
    refs, deps = self.param._setup_params(**params)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/parameterized.py", line 1686, in override_initialization
    ret = fn(self_, *args, **kw)
  File "/Users/yan/miniforge3/lib/python3.10/site-packages/param/parameterized.py", line 1939, in _setup_params
    raise TypeError(
TypeError: Markdown.__init__() got an unexpected keyword argument 'style'
```

Perhaps this is because `msprime.simulate` doesn't create mutation times and/or individuals?

**Comment by percyfal** [comment]
@hyanwong I also get this error on inferred trees when clicking on the tab "Windowed Popgen Statistics". Note that the parameter to `Markdown.__init__()` is `styles`, not `style`:
https://panel.holoviz.org/reference/panes/Markdown.html#style
